### ISSUE TITLE
Expression 

### ISSUE THREAD

**Issue by AndoniZubimendi** [cesarares/Logic-Sim#6]
If you build a circuit like this: F = (A AND B) AND (A AND B) 
The displayed expression is F = (A AND B) AND ?
If both inputs of a gate is the same and this input is something composed of some gate, the problem appears.
The Truth Table is correct.

Below is an example of the issue.

![expression](https://cloud.githubusercontent.com/assets/450249/7358342/159f5cec-ed0b-11e4-9f40-e0fe5b292bcc.png)

------------
N4IglgxgziBcDaBdANCATgewwFzqA5gIbYCmMCousIAggHYAmA4sSSKgB5wAsA7AEyoAnnADM/AByoANnBDsQDWbEEgMceNjQBXEikVw626dIC+ySnIDy27AAdbAETBQ70wiM5wAbAAZfwmKSMnIAYgpKYqjqCPoMhsZmFiBUIADCGHRQ2ACSdA64XioArN6BsOIBIMq0EcoAjNEaWrpxcC0k5pbUGVm5+bYKXCoC5aIS3CHUAEJ1cI1qzTp6qPGwHV0pcvTMrENiomUgIhXB1XJzKk0IHW2wRiam+gDuYGhkGqBQw8WHqFAnUTcSYgEjDPxVEiA4Gbb48bhSEAAg5HMHwxFQsQw5Jw2Dcfz/aEgtF4hGoTEVbFfYbAxHIip/UE00agwGHWE0slIwHFVQkvh8nn8DnowlY4mcjFCkWnKr00SMkkK1Fs7wy5Viiq88nDDWsnj+J6mUxAA
--------------

**Comment by cesarares** [comment]
The algorithm that builds the expression tree is wrong. It stops on the second pass on the same gate in order to prevent an infinite loop. 
I fixed the problem by controlling loops on the exploring branch of the expression tree.
